### PR TITLE
Check for a document in either of the first two arguments (fixes #444 and #441)

### LINKED ISSUE #444: jsdom version issues
As discussed in https://github.com/mozilla/readability/issues/376#issuecomment-385206370, the following code fails:

https://gist.github.com/bittlingmayer/7a14f3a9c17b42163d12ba7da9bd1866

```
	Content.parse( https://www.nzz.ch/international/nahost-und-afrika/komitee-zur-befreiung-der-levante-extremistengruppen-in-syrien-schliessen-sich-zusammen-ld.142403 )
Fetching  https://www.nzz.ch/international/nahost-und-afrika/komitee-zur-befreiung-der-levante-extremistengruppen-in-syrien-schliessen-sich-zusammen-ld.142403
Fetched  https://www.nzz.ch/international/nahost-und-afrika/komitee-zur-befreiung-der-levante-extremistengruppen-in-syrien-schliessen-sich-zusammen-ld.142403
Content._parse(...)
(node:5014) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'firstElementChild' of undefined
(node:5014) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### PR DESCRIPTION
**Pull request by gijsk**
This should fix #444, I believe. @davidar and/or @bittlingmayer, can you have a look if this makes sense to you? Thanks!

### CODE REVIEW

File: Readability.js [hunk 1]
```diff
@@ -26,8 +26,8 @@
  * @param {Object}       options The options object.
  */
 function Readability(doc, options) {
-  // In some older versions, people passed a URI object as the first argument. Cope:
-  if (doc && !doc.documentElement && doc.spec) {
+  // In some older versions, people passed a URI object or string as the first argument. Cope:
+  if (doc && ((!doc.documentElement && doc.spec) || typeof doc == "string")) {
```
Comment (davidar) [inline Readability.js]: Perhaps it would be worth fixing #441 at the same time and doing something like the following?

```js
if (doc && doc.documentElement) {
  // ok
} else if (options && options.documentElement) {
  doc = options;
  options = arguments[2];
} else {
  throw new Error("invalid arguments");
}
```

I think some of the tests pass in an empty object for the document though, so those would also need to be changed.

Comment (gijsk) [reply Readability.js]: Good point. Also thanks for the heads-up about the test!

I'll hold off printing a warning for now. Maybe when we publish to npm...
