### PR TITLE
Fix undefined li count

### LINKED ISSUE #791: Error during parsing | ReferenceError: li_count is not defined
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@mozilla/readability@0.4.3` for the project I'm working on.

My code runs in a browser extension and throws an error when parsing a specific website, such as [this](https://www.bbc.com/news/science-environment-65097831). The code is not imported in the usual way (as in an extension), so I'm not sure why it doesn't throw an error normally. However, it's clear that these codes is not correct.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@mozilla/readability/Readability.js b/node_modules/@mozilla/readability/Readability.js
index 35021e9..4c11d4a 100644
--- a/node_modules/@mozilla/readability/Readability.js
+++ b/node_modules/@mozilla/readability/Readability.js
@@ -2147,7 +2147,7 @@ Readability.prototype = {
               return haveToRemove;
             }
           }
-          li_count = node.getElementsByTagName("li").length;
+          var li_count = node.getElementsByTagName("li").length;
           // Only allow the list to remain if every li contains an image
           if (img == li_count) {
             return false;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### PR DESCRIPTION
**Pull request by gijsk**
This fixes #791 and enables linting so we don't make this mistake again.

### CODE REVIEW

File: JSDOMParser.js [hunk 1]
```diff
@@ -1,4 +1,3 @@
-/*eslint-env es6:false*/
```
Comment (gijsk) [inline JSDOMParser.js:1]: As far as I can tell this wasn't doing anything meaningful - there is already ES6 use in `Readability.js` (notably `Set` and `let`) so that ship has sailed.

File: test/generate-testcase.js [hunk 2]
```diff
@@ -1,3 +1,5 @@
+/*eslint-env node,mocha */
```
Comment (mikeconley) [inline test/generate-testcase.js:1]: Nit - space after `/*`

File: test/test-isProbablyReaderable.js [hunk 3]
```diff
@@ -1,3 +1,5 @@
+/*eslint-env node,mocha */
```
Comment (mikeconley) [inline test/test-isProbablyReaderable.js:1]: Nit - space after /*

File: test/test-jsdomparser.js [hunk 4]
```diff
@@ -1,3 +1,5 @@
+/*eslint-env node, mocha */
```
Comment (mikeconley) [inline test/test-jsdomparser.js:1]: Nit - space after /*

File: test/test-readability.js [hunk 5]
```diff
@@ -1,3 +1,5 @@
+/*eslint-env node, mocha */
```
Comment (mikeconley) [inline test/test-readability.js:1]: Nit - space after /*

File: test/utils.js [hunk 6]
```diff
@@ -1,3 +1,5 @@
+/*eslint-env node */
```
Comment (mikeconley) [inline test/utils.js:1]: Nit - space after /*

**Review by mikeconley — APPROVED** [review]
Does GitHub let me do r=me with nits? This looks fine to me, just some cosmetic stuff (see below). Thanks!
