### PR TITLE
Fixes #53 - Fixed dot-slash relative URI resolution.

### LINKED ISSUE #53: Fix _fixRelativeUris() to handle more cases
Source:

```html
      <p><a href="foo/bar/barz.html">link</a></p>
      <p><a href="./foo/bar/barz.html">link</a></p>
      <p><a href="/foo/bar/barz.html">link</a></p>
      <p><a href="http://test/foo/bar/barz.html">link</a></p>
      <p><a href="https://test/foo/bar/barz.html">link</a></p>
```

Generated content:

```html
        <p><a href="http://fakehost/testfoo/bar/barz.html">link</a>
        </p>
        <p><a href="http://fakehost/test./foo/bar/barz.html">link</a>
        </p>
        <p><a href="http://fakehost/foo/bar/barz.html">link</a>
        </p>
        <p><a href="http://test/foo/bar/barz.html">link</a>
        </p>
        <p><a href="https://test/foo/bar/barz.html">link</a>
        </p>
```

### PR DESCRIPTION
**Pull request by n1k0**
r? @gijsk @leibovic

### CODE REVIEW

File: test/test-readability.js [hunk 1]
```diff
@@ -60,7 +60,7 @@ describe("Test page", function() {
         host: "fakehost",
         prePath: "http://fakehost",
         scheme: "http",
-        pathBase: "http://fakehost/test"
+        pathBase: "http://fakehost/test/"
```
Comment (n1k0) [inline test/test-readability.js]: Note: it seems that's always what's returned by Gecko `newURI().spec`, though I'm not 100% sure; can someone confirm?

Comment (gijsk) [inline test/test-readability.js]: For http/https, it seems so. Not for chrome://, but I don't think we care about this case here.
